version: '3'

services:
  authdb:
    image: postgres:12-alpine
    container_name: authdb
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - authnetwork
  
  authservice:
    build: ./authservice/
    container_name: authservice
    restart: always
    depends_on:
      - authdb
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - authnetwork

volumes:
  postgres_data:

networks:
  authnetwork:
    name: authnetwork
    driver: bridge
